### ISSUE TITLE
Error in docker

### ISSUE THREAD

**Issue by jokerigno** [arehbein-git/ppTag#7]
Hi,

I tried to configure your sw in docker but I see an error when I run the container:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
File "pptag.py", line 410, in <module>
p = plexUsers()
File "/app/pptag/plexUsers.py", line 119, in __init__
self.plex = PlexServer(ppTagConfig.PLEX_URL, ppTagConfig.PLEX_TOKEN)
File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 103, in __init__
data = self.query(self.key, timeout=timeout)
File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 376, in query
response = method(url, headers=headers, timeout=timeout, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.2.100', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149de1653670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

I can't understand if something in my config.py or in my container setting. 

Can you please support me?

Ty in advance

**Comment by arehbein-git** [comment]
How do you have created the docker container? with the help of the docker-compose or using plain „docker start“.

The issue is within the docker config or your config.py. The script is not reaching the server due to a non reachable network. Make sure that the ip that you Setup in config.py is correct and that your docker container is running in the same network.

**Comment by jokerigno** [comment]
Well it was an issue in the cointair with wrong network setting.

Now I changed it, added the token from log, and the issue changed as well.

```
no token found for user CasaConcordia
Traceback (most recent call last):
File "pptag.py", line 416, in <module>
observer.start()
File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 253, in start
emitter.start()
File "/usr/local/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 110, in start
self.on_thread_start()
File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
self._inotify = InotifyBuffer(path, self.watch.is_recursive)
File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
self._inotify = Inotify(path, recursive)
File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 200, in __init__
self._add_dir_watch(path, recursive, event_mask)
File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_dir_watch
raise OSError(errno.ENOTDIR, os.strerror(errno.ENOTDIR), path)
NotADirectoryError: [Errno 20] Not a directory: b'/mnt/user/photos/'
```

As far as I understand now the problem is about resource path. But I can't understand why.

Here's the path for the pptag container
![image](https://user-images.githubusercontent.com/23552762/83969808-56bc4900-a8d2-11ea-83af-f2fe2bbc051f.png)

And here's the path for plex container
![image](https://user-images.githubusercontent.com/23552762/83969827-6f2c6380-a8d2-11ea-931d-89a36576d4d9.png)

Path are the same.

**Comment by arehbein-git** [comment]
For the docker container PHOTOS_LIBRARY_PATH needs to be set to "/Photos“ as it is mounted in the container under this path.

PHOTOS_LIBRARY_PATH_PLEX needs to be the exact path that you have setup inside plex.

**Comment by jokerigno** [comment]
Great! Solved!
